const ArtistNames = [
  'Timmy Lee',
  'Jaikwon Myung',
  'Owen Planchart',
  'Mirko Febbo',
  'Pietro Bardini',
  'Felix Loftus',
  'Yu Hsuan Liao',
  'Chris Newth',
  'Lou Terry',
  'Yishuai ',
  'Ho Yin',
  'Armando González Sosto',
  'JG Legion',
  'Eden Chahal',
  'Akinsola Lawanson',
  'Harry Wakeling',
  'James Lawton',
  'Jonas Grünwald',
  'Max Jala',
  'Jinyuan Li',
  'Haotong Qu',
  'Ivy Vo',
  'Robert Hillson',
  'George Micah Kuhn',
  'Maite de Orbe',
  'Alexander MacKinnon',
  'Shai Rapoport',
  'Betty Li',
  'Zhichen Gu',
  'Hannah',
  'Cheng Yang',
  'Camila Colussi',
  'Hankun Yu',
  'Hankun Yu',
  'Yundan Qiu',
  'Marisa Di Monda',
  'Katie Tindle',
  'Catarina Rodrigues',
  'Mengdi Li',
  'Alexander Velderman',
  'HumYeh',
  'kris cirkuit',
  "Kerrie O'Leary",
  'Eleanor Edwards',
  'Noa Geras',
  'Karen Okpoti',
  'with.lasers',
  'Jingyi Chen',
  'Xinyu Sun',
  'Chaojing Li',
  'Marlena Kepa',
  'Xi Sun',
  'Rita Cabrito',
  'Catherine Chapman',
  'Seyeon Park ',
  'Renato Correa de Sampaio',
  'Yuqian Sun',
  'Flo Yuting-Zhu',
  'Alexandra Pfammatter',
  'Siyuan Wu',
  'Qike Shi',
  'Samuel Turner',
  'Yue Chen',
  'Shiqi',
  'Keita Ikeda',
  'Bokani Tshidzu',
];

export default ArtistNames;
